### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by azor32** [Tarcontar/ArduinoMDB#1]
Hello. There are missing files that are meant to be in the library (errors when trying to compile). Do you have a link to the missing files or can you post them? eg: "UART.hpp"

**Comment by Tarcontar** [comment]
Hi, these files are in my other repository called UART. I need to add this one as a submodule soon.

**Comment by azor32** [comment]
Ahh thanks. The compiler has an error about logger.hpp not being available.

**Comment by Tarcontar** [comment]
Thats the Logger repository. I made this stuff for a bigger project and just splittet them into single repositorys to publish them.

**Comment by azor32** [comment]
Ok. Is this file in a private repository? Also, I'm getting other errors while compiling. I've attached a txt file with the Arduino IDE compiler error:
[errors.txt](https://github.com/Tarcontar/ArduinoMDB/files/2656850/errors.txt)

**Comment by Tarcontar** [comment]
No, the Logger repository is also public. I always compiled it with cmake and command line tools, not with the arduino ide. Need to check if i get it working in the IDE.

**Comment by azor32** [comment]
Thanks, have all the files now. The Arduino IDE is having issues compiling as below:

sample:16: error: 'class CoinChanger' has no member named 'SetSerial'

   changer.SetSerial(serial);

           ^

sample:18: error: 'class BillValidator' has no member named 'SetSerial'

   validator.SetSerial(serial);

             ^

C:\Users\User\Desktop\desktop old\Evollve\Business Operations\Code\Control 24V Vending Motor with Limit Switch\Arduino MDB Controller\ArduinoMDB-master\sample\sample.ino: In function 'void loop()':

sample:25: error: no matching function for call to 'CoinChanger::Update()'

   unsigned long change = changer.Update();

                                         ^

C:\Users\User\Desktop\desktop old\Evollve\Business Operations\Code\Control 24V Vending Motor with Limit Switch\Arduino MDB Controller\ArduinoMDB-master\sample\sample.ino:25:41: note: candidate is:

In file included from C:\Users\User\Desktop\desktop old\Evollve\Business Operations\Code\Control 24V Vending Motor with Limit Switch\Arduino MDB Controller\ArduinoMDB-master\sample\sample.ino:1:0:

C:\Users\User\Documents\Arduino\libraries\ArduinoMDB-master/CoinChanger.h:17:7: note: void CoinChanger::Update(long unsigned int&)

  void Update(unsigned long &change);

       ^

C:\Users\User\Documents\Arduino\libraries\ArduinoMDB-master/CoinChanger.h:17:7: note:   candidate expects 1 argument, 0 provided

Using library ArduinoMDB-master at version 1.0.2 in folder: C:\Users\User\Documents\Arduino\libraries\ArduinoMDB-master 
Using library SD at version 1.1.1 in folder: C:\Program Files (x86)\Arduino\libraries\SD 
Using library Wire at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire 
Using library SoftwareSerial at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial 
Using library SPI at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SPI 
exit status 1
'class CoinChanger' has no member named 'SetSerial'

**Comment by Tarcontar** [comment]
Ill try to get it working with the IDE later.

**Comment by Tarcontar** [comment]
Its not very clean atm, but i can compile it now with the arduino IDE with ArduinoMegaADK selected.
Havent the hardware at hand to test it properly though...

**Comment by azor32** [comment]
Did you need to make any changes to the code?

**Comment by azor32** [comment]
I can compile your new code and library files.  Is it absolutely necessary to have the resistors in the circuit? Should this work plugging the tx and rx directly from the coin changer to pin 18 and 19?

**Comment by Tarcontar** [comment]
No it wont work without the provided circuit, since the arduino pins cant provide the required current for driving the devices. The signals need to be around 200mA to be recognized by the MDB Devices

**Comment by azor32** [comment]
Thanks for that, I'll build the circuit from your diagram.

**Comment by azor32** [comment]
Which PNP transistors are suitable?

**Comment by Tarcontar** [comment]
Well dont think that is very restrictive, think any pnp transistor that can handle about 300mA should work.
