### ISSUE TITLE
The project is not built

### ISSUE THREAD

**Issue by vallemar** [Tarcontar/ArduinoMDB#2]
Hi @Tarcontar 

When I try to validate the project I have many errors, All the variables https://github.com/Tarcontar/ArduinoMDB/blob/master/UART.cpp#L66 `RXEN2`,` RXEN3` ... are not declared.

All these methods also fail: https://github.com/Tarcontar/ArduinoMDB/blob/master/UART.cpp#L307
```
ArduinoMDB\UART.cpp: In function 'void USART0_RX_vect()':
ArduinoMDB\UART.cpp:307:5: warning: 'USART0_RX_vect' appears to be a misspelled 'signal' handler, missing '__vector' prefix [-Wmisspelled-isr]
 ISR(USART0_RX_vect)
     ^
ArduinoMDB\UART.cpp: In function 'void USART1_RX_vect()':
ArduinoMDB\UART.cpp:312:5: warning: 'USART1_RX_vect' appears to be a misspelled 'signal' handler, missing '__vector' prefix [-Wmisspelled-isr]
 ISR(USART1_RX_vect)
     ^
ArduinoMDB\UART.cpp: In function 'void USART2_RX_vect()':
ArduinoMDB\UART.cpp:317:5: warning: 'USART2_RX_vect' appears to be a misspelled 'signal' handler, missing '__vector' prefix [-Wmisspelled-isr]
 ISR(USART2_RX_vect)
     ^
ArduinoMDB\UART.cpp: In function 'void USART3_RX_vect()':
ArduinoMDB\UART.cpp:322:5: warning: 'USART3_RX_vect' appears to be a misspelled 'signal' handler, missing '__vector' prefix [-Wmisspelled-isr]
 ISR(USART3_RX_vect)
     ^
```

I have searched their repository: https://github.com/Tarcontar/UART/blob/master/UART.cpp but it seems that it is the same

**Comment by Tarcontar** [comment]
Hi, I haven't touched that project in quite a while. But you might have to install the Arduino ide with the Arduino mega drivers.

**Comment by vallemar** [comment]
Excuse me, you're absolutely right. I was just trying to take a look at the code and I had the `uno` board on, thank you very much!

**Comment by Tarcontar** [comment]
No problem, let me know if you encounter any other issues.:)
