### ISSUE TITLE
help with project

### ISSUE THREAD

**Issue by Fishtronics** [Tarcontar/ArduinoMDB#4]
Hi

I have tryed connecting the coin acceptor axactly as displayed on your new picture uyploaded your code:
``#include <SoftwareSerial.h>
#include "BillValidator.h"
#include "CoinChanger.h"
#include "MDBSerial.h"

MDBSerial mdb(0);
CoinChanger changer(mdb);
BillValidator validator(mdb);

SoftwareSerial serial(3, 4);

void setup()
{
  serial.begin(9600);
  serial.println("test");

  changer.Reset();
  validator.Reset();
  serial.println("VMC###############");
}

void loop()
{ changer.Reset();
  unsigned long change;
  changer.Update(change);
  validator.Update(change);
  delay(2000);
}``
doesnt seem to work for me.
Attached a logic analiser can only see "test" displaying on pin 4 but noting on Tx1/pin18?

can you please help me?
Kind regards
Fishtronics

**Comment by Tarcontar** [comment]
Hi, could you post some pictures on how you set up your coinchanger? Especally of the wiring and connection to the 6 pin MDB connector.

**Comment by Fishtronics** [comment]
drew my setup
![mySetup](https://user-images.githubusercontent.com/94795272/142878113-2e314cb8-a175-4566-ace7-82a43fe74769.png)

**Comment by Tarcontar** [comment]
Please change the code back to the sample!
You configured MDBSerial from mdb(1) to mdb(0) which is wrong since UART0 is used for the communication between arduino and the PC and thus should not be used. Also you configured SoftwareSerial from serial(0, 1) to serial(3, 4) this way your arduino is no longer able to talk to the connected PC.

**Comment by Fishtronics** [comment]
Hi tried again with changes, nothing seems to be transmitting true Tx1 (checked with logic analyzer) which should be sending poll commands or reset commands. The only thing I can see on serial monitor is "test".
 program seems to get stuck at some place...

**Comment by Tarcontar** [comment]
Hi, how do you power your Arduino? Since the 5v line connected to the MdB circuit actually needs a few hundred milli amps (I think around 100-200mA / connected device). Try to hook it up to a sufficient power supply and also power the Arduino with it.

**Comment by Fishtronics** [comment]
I think i found it could it be that mdb.begin(); is missing?

**Comment by Fishtronics** [comment]
![ללא שם](https://user-images.githubusercontent.com/94795272/143135948-2accfa3d-8250-444e-8970-63c95755d318.png)

**Comment by Fishtronics** [comment]
![ללא שם](https://user-images.githubusercontent.com/94795272/143136091-a07f6f88-afda-42a7-9261-5957b4f6cb7a.png)

**Comment by Fishtronics** [comment]
is this how the tx1 output should look like without anny device conected?

**Comment by Tarcontar** [comment]
That looks indeed promising. So it was the missing .begin?

**Comment by Fishtronics** [comment]
Hi I think I am almost there:-) yust can you please explain me how I can display the debug for example in CoinChanger.cpp on the seial monitor or perhaps elsewhere?
       `debug << F("## CoinChanger ##") << endl;
	debug << F("credit: ") << m_credit << endl;
	debug << F("country: ") << m_country << endl;
	debug << F("feature level: ") << (int)m_feature_level << endl;
	debug << F("coin scaling factor: ") << (int)m_coin_scaling_factor << endl;
	debug << F("decimal places: ") << (int)m_decimal_places << endl;
	debug << F("coin type routing: ") << m_coin_type_routing << endl;`

**Comment by Tarcontar** [comment]
Hi, 
you have to use the logger class and configure it accordingly:
```
int uart = 0; // the uart port to communicate to the PC (0 if you want to use USB connection)

Logger logger = new Logger(0);
logger.SetUART(new UART(0));

```

**Comment by Fishtronics** [comment]
Hi
sorry for my late feedback.
I am still strugeling with the logger class dont see any info on the arduino serial monitor?

see below my code:`
#include <SoftwareSerial.h>
#include "BillValidator.h"
#include "CoinChanger.h"
#include "MDBSerial.h"

Logger logger = new Logger(0);
int uart = 0; // the uart port to communicate to the PC (0 if you want to use USB connection)
MDBSerial mdb(1);
CoinChanger changer(mdb);
SoftwareSerial serial(0, 1);
unsigned long change;
void setup()
{ logger.SetUART(new UART(0));
  serial.begin(9600);
  serial.println("test");
  mdb.begin();
  changer.Reset();
  serial.println("VMC###############");
  changer.Update(change);
  changer.Dispense(10);
}

void loop()
{ //changer.Reset();
  
  changer.Update(change);
  serial.println(changer.GetCredit());
  delay(2000);
}`

**Comment by Tarcontar** [comment]
Hi, i am quite busy atm but I will try to clean up this repository over the holidays to make it more usable.

**Comment by Fishtronics** [comment]
Thanks a lot!!
That will be great!!

**Comment by Tarcontar** [comment]
Hi, i just updated the sample .ino file. Please check it out and let me know if it works now for you.

**Comment by Fishtronics** [comment]
Fantastic it works!!
I also added Logger::SetDebug(1); so i can follow the debug.,
The only problem is the dispence function its not working .
if  a 5 coin is inserted it should despensed  see my code below:

` //#include "BillValidator.h"
#include "CoinChanger.h"
#include "MDBSerial.h"

MDBSerial mdb(1);
CoinChanger changer(mdb);
//BillValidator validator(mdb);
UART uart;
unsigned long change;
void setup()
{
  mdb.begin();

  uart = UART(0);
  uart.begin();
  Logger::SetUART(&uart);
 Logger::SetDebug(1);
  changer.Reset();
  //validator.Reset();
  uart.println("###############");
}

void loop()
{
  
  changer.Update(change);
  //changer.GetDispensedValue();
  uart.print("credit: ");
  uart.print(changer.GetCredit());
  uart.println(" ");
  if (changer.GetCredit() >= 500) {
    changer.Dispense(500);
    changer.Update(change);
  }
  delay(200);
}`

see below the serial output:
`## CoinChanger ##
credit: 0
country: 4982
feature level: 3
coin scaling factor: 10
decimal places: 2
coin type routing: 63
coin type credits: 1 5 10 20 50 100 0 0 0 0 0 0 0 0 0 0 
tube full status: 0
tube status: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
software version: 1541
optional features: 15
alternative payout supported: 1
extended diagnostic supported: 1
mauall fill and payout supported: 1
file transport layer supported: 1
######
CC: INIT COMPLETED
CC: RESET COMPLETED
###############
CC: poll got ack
credit: 0 
CC: poll got ack
credit: 0 
CC: poll got ack
credit: 0 
CC: poll got ack
credit: 0 
CC: poll got ack
credit: 0 
CC: poll got ack
credit: 0 
credit: 500 

????SOMEHOW GETS STUCK OVER HERE
`

**Comment by Tarcontar** [comment]
Hi, i had a quite similar issue at the beginning. Please make sure you provide sufficient power to the coin changer. It might respond properly in the beginning, but once the dispense routine starts it requires quite some power.

I do not have a CoinChanger at hand anymore, so cant really test anything.

Hope that helps.

**Comment by Fishtronics** [comment]
Hi
HAPPY NEWYEAR!!
Got it all working!!
You are unbelieveble!!
will maybe  try to adapt the library  for arduino nano (wich is a much cheaper and lighter board)
maybe can you give me some suggestions (maybe log over softserial?)
Thanks

**Comment by Tarcontar** [comment]
Hi,
happy new year for you too :)
Great to hear that it is now working for you!

For the nano you have indeed to use softserial since afaik it only has a single UART which is needed for the MDB communication.
You also wont be able to connect it to the PC with a single USB cable and see the debug output anymore.

I will close this issue now.

You can open a new one if you have trouble adapting to the nano but I can not guarantee I find the time to help you out.

Regards
Tarcontar

**Comment by admindotnu** [comment]
> drew my setup ![mySetup](https://user-images.githubusercontent.com/94795272/142878113-2e314cb8-a175-4566-ace7-82a43fe74769.png)

Can you verify this one, is it still correct

**Comment by Tarcontar** [comment]
Hi, R6 should be 5Ohm not 10Ohm.
Otherwise it seems fine.
